import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Map from '../components/LeafletMap'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scoo Tech GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Herzlich Willkommen bei der Scoo Tech GmbH
        </h1>

        <Image src="escooter.jpg"></img>


        <div className={styles.grid}>
          <Link href="/map">
            <a className={styles.card}>
              <h2>Preisberechner &rarr;</h2>
              <p>Dann nutzen Sie gerne unseren Preisberechner!</p>
            </a>
          </Link>

          <Link href="/impressum">
            <a className={styles.card}>
              <h2>Impressum &rarr;</h2>
              <p>Hier gelangen Sie zum Impressum!</p>
            </a>
          </Link>
        </div>
      </main>

     

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
